on:
  pull_request:

name: Preview Deployment

jobs:
  preview-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
      - run: yarn build

      - id: karrotmini-deployment
        uses: karrotmini/deployment-site@beta
        with:
          api-key: ${{ secrets.KARROTMINI_API_KEY_TEST }}
          build-output-directory: ./build
          preview-id: gh-pr-${{ github.event.pull_request.number }}
          bundle-upload-http-endpoint: https://0a5e-211-244-135-48.ngrok.io/console/miniapps/bundle/upload-preview
