on:
  pull_request:

name: Preview Deployment

jobs:
  preview-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
      - run: yarn build

      - id: karrotmini-deployment
        uses: karrotmini/deployment-site@add-preview-deployment-actions
        with:
          api-key: ${{ secrets.KARROTMINI_API_KEY }}
          build-output-directory: ./unknown
          preview-id: gh-pr-${{ github.event.pull_request.number }}
