on:
  pull_request:

name: Preview Deployment

jobs:
  preview-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
      - run: yarn build

      - id: karrotmini-deployment
        uses: karrotmini/deployment-site@310e9315869e5ce5d7e0a523c0a8bed86b3ca62d
        with:
          api-key: ${{ secrets.KARROTMINI_API_KEY }}
          build-output-directory: ./build
          preview-id: gh-pr-${{ github.pull_request.number }}
